apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: default
spec:
  type: LoadBalancer  # Cria ELB público; para interno, use ClusterIP
  selector:
    app: php-app  # Seleciona os pods do deployment
  ports:
  - port: 80  # Porta externa
    targetPort: 80  # Porta do container
    protocol: TCP
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Ou "alb" para Application LB