name: CI - Build, Scan e Push da Imagem Docker

on:
  push:
    branches:
      - main 

env:
  
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/php-hello-app 
  DOCKER_TAG: ${{ github.sha }} # Usaremos o SHA do commit como tag para garantir unicidade

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Construir Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false 
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          load: true 
      
      - name: Run Trivy vulnerability scanner
        
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          format: 'table'
          
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'

      
      - name: Fazer Push da Imagem para o Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_IMAGE }}:latest # Também faz o push com a tag 'latest'